### ISSUE TITLE
关于硬件预取器中delta的计算

### ISSUE THREAD

**Issue by cairenhao** [miaochenlu/learn_prefetcher#1]
大佬您好，我想向您询问下有关硬件预取器中，访存地址间的delta计算方法，在SPP预取算法中，当前的块地址计算方法为：stride_t current_block = (request_addr % pageBytes) / blkSize，我无法理解为什么以这种方式计算当前块地址，希望能够得到您的指点，非常感谢🙇‍。

**Comment by miaochenlu** [comment]
这应该就是位于当前page的第几个块的意思。

**Comment by cairenhao** [comment]
好勒，感谢
